/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as GrievanceCellRouteImport } from './routes/grievance-cell'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AiQuizRouteImport } from './routes/ai-quiz'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AccreditationRouteImport } from './routes/accreditation'
import { Route as AcademicPlannerRouteImport } from './routes/academic-planner'
import { Route as IndexRouteImport } from './routes/index'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceCellRoute = GrievanceCellRouteImport.update({
  id: '/grievance-cell',
  path: '/grievance-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AiQuizRoute = AiQuizRouteImport.update({
  id: '/ai-quiz',
  path: '/ai-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AccreditationRoute = AccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPlannerRoute = AcademicPlannerRouteImport.update({
  id: '/academic-planner',
  path: '/academic-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-planner': typeof AcademicPlannerRoute
  '/accreditation': typeof AccreditationRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-quiz': typeof AiQuizRoute
  '/alumni': typeof AlumniRoute
  '/attendance': typeof AttendanceRoute
  '/broadcast': typeof BroadcastRoute
  '/courses': typeof CoursesRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/grievance-cell': typeof GrievanceCellRoute
  '/hostel': typeof HostelRoute
  '/internships': typeof InternshipsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notices': typeof NoticesRoute
  '/placement': typeof PlacementRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-planner': typeof AcademicPlannerRoute
  '/accreditation': typeof AccreditationRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-quiz': typeof AiQuizRoute
  '/alumni': typeof AlumniRoute
  '/attendance': typeof AttendanceRoute
  '/broadcast': typeof BroadcastRoute
  '/courses': typeof CoursesRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/grievance-cell': typeof GrievanceCellRoute
  '/hostel': typeof HostelRoute
  '/internships': typeof InternshipsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notices': typeof NoticesRoute
  '/placement': typeof PlacementRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-planner': typeof AcademicPlannerRoute
  '/accreditation': typeof AccreditationRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-quiz': typeof AiQuizRoute
  '/alumni': typeof AlumniRoute
  '/attendance': typeof AttendanceRoute
  '/broadcast': typeof BroadcastRoute
  '/courses': typeof CoursesRoute
  '/credentials': typeof CredentialsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/grievance-cell': typeof GrievanceCellRoute
  '/hostel': typeof HostelRoute
  '/internships': typeof InternshipsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notices': typeof NoticesRoute
  '/placement': typeof PlacementRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/subjects': typeof SubjectsRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-planner'
    | '/accreditation'
    | '/ai-insights'
    | '/ai-quiz'
    | '/alumni'
    | '/attendance'
    | '/broadcast'
    | '/courses'
    | '/credentials'
    | '/dashboard'
    | '/exams'
    | '/faculty'
    | '/fees'
    | '/grievance-cell'
    | '/hostel'
    | '/internships'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/messages'
    | '/notices'
    | '/placement'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-planner'
    | '/accreditation'
    | '/ai-insights'
    | '/ai-quiz'
    | '/alumni'
    | '/attendance'
    | '/broadcast'
    | '/courses'
    | '/credentials'
    | '/dashboard'
    | '/exams'
    | '/faculty'
    | '/fees'
    | '/grievance-cell'
    | '/hostel'
    | '/internships'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/messages'
    | '/notices'
    | '/placement'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/academic-planner'
    | '/accreditation'
    | '/ai-insights'
    | '/ai-quiz'
    | '/alumni'
    | '/attendance'
    | '/broadcast'
    | '/courses'
    | '/credentials'
    | '/dashboard'
    | '/exams'
    | '/faculty'
    | '/fees'
    | '/grievance-cell'
    | '/hostel'
    | '/internships'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/messages'
    | '/notices'
    | '/placement'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicPlannerRoute: typeof AcademicPlannerRoute
  AccreditationRoute: typeof AccreditationRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiQuizRoute: typeof AiQuizRoute
  AlumniRoute: typeof AlumniRoute
  AttendanceRoute: typeof AttendanceRoute
  BroadcastRoute: typeof BroadcastRoute
  CoursesRoute: typeof CoursesRoute
  CredentialsRoute: typeof CredentialsRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  FacultyRoute: typeof FacultyRoute
  FeesRoute: typeof FeesRoute
  GrievanceCellRoute: typeof GrievanceCellRoute
  HostelRoute: typeof HostelRoute
  InternshipsRoute: typeof InternshipsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NoticesRoute: typeof NoticesRoute
  PlacementRoute: typeof PlacementRoute
  ReportsRoute: typeof ReportsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  SubjectsRoute: typeof SubjectsRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance-cell': {
      id: '/grievance-cell'
      path: '/grievance-cell'
      fullPath: '/grievance-cell'
      preLoaderRoute: typeof GrievanceCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-quiz': {
      id: '/ai-quiz'
      path: '/ai-quiz'
      fullPath: '/ai-quiz'
      preLoaderRoute: typeof AiQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accreditation': {
      id: '/accreditation'
      path: '/accreditation'
      fullPath: '/accreditation'
      preLoaderRoute: typeof AccreditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-planner': {
      id: '/academic-planner'
      path: '/academic-planner'
      fullPath: '/academic-planner'
      preLoaderRoute: typeof AcademicPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicPlannerRoute: AcademicPlannerRoute,
  AccreditationRoute: AccreditationRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiQuizRoute: AiQuizRoute,
  AlumniRoute: AlumniRoute,
  AttendanceRoute: AttendanceRoute,
  BroadcastRoute: BroadcastRoute,
  CoursesRoute: CoursesRoute,
  CredentialsRoute: CredentialsRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  FacultyRoute: FacultyRoute,
  FeesRoute: FeesRoute,
  GrievanceCellRoute: GrievanceCellRoute,
  HostelRoute: HostelRoute,
  InternshipsRoute: InternshipsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NoticesRoute: NoticesRoute,
  PlacementRoute: PlacementRoute,
  ReportsRoute: ReportsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  SubjectsRoute: SubjectsRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
